### ISSUE TITLE
Video is still playing but hidden when a new video is previewed

### ISSUE THREAD

**Issue by some1so** [Oil3/Webm-QuickLook-Plug-In#3]
This is great, thanks!
I'm using the Autoplay version, and I found one issue.
I select a webm, hit spacebar, and it previews with sound playing, works fine. 
While it's playing, select a second webm with arrow keys or pointer, the first one will hide but the sound will keep playing, and the second webm will load and play with sound. 
If I pick another webm, the first one will stop, the second will hide and keep playing, and the third will play normally.
Closing the QL window will stop everything.
I'm on 15.2, Intel Macbook Pro.
Thanks again

**Comment by Oil3** [comment]
HI @some1so , thanks for the precise bug report!  

I fixed it on my side, let me know if it works for you, make sure to delete the previous version.
https://github.com/Oil3/Webm-QuickLook-Plug-In/releases/tag/WebmQuicklook-2025jan-backgroundplayfixed-autoplay

**Comment by some1so** [comment]
Thank you for the fix!
I tested it, but unfortunately found an issue when I play a webm that has been previously been played.
It looks complicated in the repro steps, but essentially it is just that the previous webm is retaining it's state when hidden, and if played again will just display in that same state.  
It's a small thing, and only shows up when aggressively clicking or arrowing back and forth in the list, and it sorts itself out with a few clicks, but I thought you'd want to know :)
Repro steps:
Play webm #1 - plays fine.
While webm #1 is still playing, play webm #2. Webm #1 stops, webm #2 plays fine.
While webm #2 is still playing, play webm #1 again. Webm #2 hides but continues to play. Webm #1 is displayed, but paused at the time that the switch happened.
Play webm #2 again, and it displays while still playing. 
Play webm #1 again, and it is still paused while webm #2 continues to play.
Play webm #3, and webm #2 stops playing, webm #1 is hidden, and webm #3 plays fine.
Play webm #1 again, still paused, webm #3 is hidden but continues to play.
Play webm #3 again, it displays and continues playing while webm #1 is hidden.
Play webm #4, it plays fine while webm #3 is hidden and paused.
Play webm #1 again, it now plays fine while webm #4 is hidden and paused.

Thanks
 
Thanks

**Comment by Oil3** [comment]
It's taking more than time than expected,  
I'v spent quite some time trying to fix it and it's quite a mess,   
the closest I got so far was to fixing this issue is strictly when the finder is itself with the side preview.  
Alternatively, without autoplay worked too, but I understand it's not the same. 
There is one workaround possible, but I first want to try something very simple: either I find out how to have the panel trigger pause on arrow key (that does work in the 'app' of the plugin, but in preview it doesn't -extensions are quite sandboxed.  
So the idea now is to find out which 'NSEventmask' we could use to trigger the pause.   
Pausing is easy, but pausing the hidden one pauses the frontmost one too.  
And every conventional pauseallmedias, closeallmedia, reload etc don't work.
All this to say, I'm on it. 

Apart of this, all good? Always snappy, no crash?

**Comment by some1so** [comment]
Hi
Yes, it's very usable and I haven't seen other problems with it. If the pause problem shows up I just clear it by going up or down a couple of webms in the list and it works fine. So no need to rush or feel pressure to get a fix out quickly :)

**Comment by Oil3** [comment]
Thanks for kind words, 
I think I'm getting there, now the issue is kinda gone but then if in the Finder you have the preview pane (usually in column view), then sometimes (???) it's playing twice.

**Comment by Oil3** [comment]
@some1so  Hi, fixed now, let me know if it works as intende for you as well,

direct-download: https://github.com/Oil3/Webm-QuickLook-Plug-In/releases/download/webM-feb2025/Webm.Quicklook.feb2025.universal.binary.zip

**Comment by some1so** [comment]
Hi
I installed the new version, and it works great, except for the pause issue, which still happens when reversing :)
But, it's easy to clear it, and not a big problem, so it's great, and much better than other options.
Thanks for your attention and efforts, I understand it's a pretty restrictive environment to code in. I'll go ahead and close this now as I am happy with it.
Thanks

**Comment by some1so** [comment]
Hi
I just deleted and reinstalled it to make sure.
I don't get the "hidden and still playing" problem anymore. I get the Pause issue - when I go back to a video that was previously playing, it is paused where it was before - 
play vid 1, after a couple of seconds arrow down to play vid 2.  Let it play a couple of seconds and arrow up to vid 1 again. Vid 1 is paused where it was when I left it, and doesn't restart from beginning.

**Comment by Oil3** [comment]
hi, @some1so ,
ok, what I got now is `play vid 1,  eventually arrow down to play vid 2.  Eventually arrow up to vid 1 again. Vid 1 resumes from where it was.`
thx for your detailed explanations,

https://github.com/Oil3/Webm-QuickLook-Plug-In/releases/tag/march2025
